# Created by Claude Code on 2025-10-28
# Purpose: Conda environment for markdown2pdf project
# Context: Setting up a Python environment for a CLI tool that converts Markdown to PDF
# using weasyprint for high-quality PDF generation

name: markdown2pdf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - weasyprint>=60.0
      - markdown>=3.5
      - pygments>=2.17
      - click>=8.1
